#!/usr/bin/env python3
"""Reproduce the original integer sine lookup. No third-party samples."""
import math
from pathlib import Path
root = Path(__file__).resolve().parents[1]
rows = [", ".join(str(round(math.sin((i+j)*2*math.pi/256)*32767)) for j in range(16)) for i in range(0,256,16)]
(root / "core/src/sine_table.inc").write_text("// Original 256-sample sine lookup, generated by scripts/generate_sine.py.\n" + ",\n".join(rows) + "\n")
